In [1]:

import numpy as np

In [3]:
arr = np.array([1, 2,3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
arr1 = np.array((1, 2, 3, 4, 5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr2 = np.array([8])
print(arr2)

[8]


In [9]:
#2d array
arr3 = np.array([[1, 2, 3, 4],[2, 3, 4, 8]])
print(arr3)

[[1 2 3 4]
 [2 3 4 8]]


In [15]:
#2d array
arr4 = np.array([[2, 3, 5, 6],[2, 2, 1,4]])
print(arr4)

[[2 3 5 6]
 [2 2 1 4]]
